### ISSUE TITLE
Anybody there?

### ISSUE THREAD

**Issue by jan-brinkmann** [jareware/docker-volume-backup#38]
Hi,

is still anybody there maintaining this project?
There are a number of pull request that need to be done.

Regards
Jan

**Comment by jareware** [comment]
We're here, just busy with work, and life. 🙂 

Sorry for slacking on the PR's, will try to get them in ASAP!

**Comment by jan-brinkmann** [comment]
Glad to hear!

Let me know if there is anything I can do. E.g., Release notes, Docker images, etc.

**Comment by jareware** [comment]
@jan-brinkmann there's now a new release, and it's pushed up to Docker Hub as well (do note the new image owner, though).

Let's make sure the next one doesn't take as long. 😅 

Thanks for your patience!
