### ISSUE TITLE
Support local S3

### ISSUE THREAD

**Issue by Edo78** [jareware/docker-volume-backup#40]
Hi, I use minio on my NAS to have S3 bucket in my LAN

Can you consider to support other S3 providers and local S3?

Thank you

**Comment by m90** [comment]
You can pass a non-AWS endpoint using [`AWS_EXTRA_ARGS`](https://github.com/jareware/docker-volume-backup#configuration) which should allow you to use anything that is S3 compatible, including MinIO.

**Comment by jan-brinkmann** [comment]
@m90, whould it be possible adding an example to the `test` folder?
There are a number of examples for various functionalities. A `docker-compose.yml` including both `minio` and a `docker-volume-backup` container whould be great!

**Comment by m90** [comment]
@jan-brinkmann I'm not a contributor to this repo or affiliated in any other way, so you'll have to ask others I guess.

**Comment by jareware** [comment]
Thanks for the tip @m90, I added a note about this to the docs for `AWS_EXTRA_ARGS`!
